log_level: INFO
redis:
  host: redis
  port: 6379
  stream_id: stream1
  input_stream_prefix: objecttracker
  output_stream_prefix: detectionselector
prometheus_port: 8000
min_confidence: 0.2 # minimum confidence below which a message is sent
min_width: 0.001 # minimum bounding box width below which a message is sent
min_height: 0.001 # minimum bounding boxheight below which a message is sent
max_detections: 20 # maximum number of detections in a message above which a message is sent
time_past: 1d # e.g. 1d, 5h, 10m, 30s time interval after which a message is sent even if no other criteria are met