log_level: INFO
redis:
  host: redis
  port: 6379
  stream_id: stream1
  input_stream_prefix: objecttracker
  output_stream_prefix: detectionselector
prometheus_port: 8000
min_confidence: 0.2
min_width: 0.001
min_height: 0.001
max_detections: 20
time_past: 1d