#!/bin/bash
set -e

# Create 
if [ "$1" = "configure" ]; then

    cd "/opt/starwit/sae-ai-control"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt    

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/sae-ai-control <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/sae-ai-control
source .venv/bin/activate

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/sae-ai-control    

    # link settings file from etc
    cd /opt/starwit/sae-ai-control
    ln -sf /etc/starwit/sae-ai-control/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start sae-ai-control.service        
    systemctl enable sae-ai-control.service
fi

#DEBHELPER#

exit 0