#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # Stop the service
    systemctl stop sae-ai-control.service

    # Disable the service
    systemctl disable sae-ai-control.service

    # Remove the service file
    rm -f /etc/systemd/system/sae-ai-control.service

    systemctl daemon-reload

    # Remove the wrapper script
    rm -f /usr/local/bin/sae-ai-control
    
    # Remove application directory
    rm -rf /opt/starwit/sae-ai-control

    # Remove config files directory
    rm -rf /etc/starwit/sae-ai-control
fi

#DEBHELPER#

exit 0